server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abcd1234
mybatis:
  #configuration:
    #map-underscore-to-camel-case: true #开启驮峰命名
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:cn/**/mapper/*.xml
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    cn.com.sparknet: debug
